name: Manual WF
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deployment version'
        required: true
        default: '1.0.0'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
jobs:
    display-version:
        runs-on: self-hosted
        steps:
            - name: Print version
              run: echo "Version to deploy ${{ inputs.version }}"
            - name: Print environment
              run: echo "Environment to deploy ${{ inputs.environment }}"