name: Checkout Branch Workflow
on:
    push:
        branches:
            - main

jobs:
    checkout-branch:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: show branch
              run: git branch
            - name: list files
              run: ls -l
