name: Checkout Branch Workflow
on:
    push:
        branches:
            - main


jobs:
    checkout-branch:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - run: git branch

