name: Filter Branch Workflow
on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'


jobs:
    checkout-branch:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4

            - run: git branch

