name: Python Application CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted
        strategy:
          max-parallel: 3
          matrix:
            python-version: [3.11, 3.12, 3.13]
        steps:
        - uses: actions/checkout@v4

        - name: Install Python 
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
        - name: Run tests
          run: pytest --junitxml=test-results.xml

        - name: Run application
          run: python app.py > output.txt

        - name: Upload test results
          uses: actions/upload-artifact@v4
          with:
            name: test-results-${{matrix.python-version}}
            path: test-results.xml
        
        - name: Upload app output 
          uses: actions/upload-artifact@v4
          with:
            name: app-output--${{matrix.python-version}}
            path: output.txt
            retention-days: 14
          