name: Python Application CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v4

        - name: Install Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run tests
          run: pytest --junitxml=test-results.xml

        - name: Run application
          run: python app.py > output.txt

        - name: Upload test results
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: test-results.xml
        - run: coverage run -m pytest -v
        - name: Coverage Badge
          uses: tj-actions/coverage-badge-py@v1.8
        - run: |
            git add coverage.svg
            git commit -m "Add code covarage"
            git push

        - name: Upload app output
          uses: actions/upload-artifact@v4
          with:
            name: app-output
            path: output.txt
            retention-days: 14