name: Secret Handling WF
on:
    workflow_dispatch: 
jobs:
    say-hello:
        runs-on: self-hosted
        env:
            MYVAR1: "ENV_VAR_1"
            MYVAR2: "ENV_VAR_2"
            SECRET_KEY: ${{ secrets.MY_EXAMPLE_SECRE }}
        steps:
            - name: Print env vars
              run: echo $MYVAR1 $MYVAR2
            - name: Print message
              run: echo $SECRET_KEY