name: Secret Handling WF
on:
    workflow_dispatch: 
jobs:
    say-hello:
        runs-on: self-hosted
        env:
            MYVAR1: "ENV_VAR_1"
            MYVAR2: "ENV_VAR_2"
        steps:
            - name: Print injected env vars
              run: echo $MYVAR1 $MYVAR2
            
            - name: Print secret
              run: echo  ${{ secrets.MY_EXAMPLE_SECRE }}
            
            - name: print repository variable 
              run: echo ${{ vars.MY_GITHUB_VAR }}