# Deploys to S3
# dev: bucket-dev, stage: bucket-stage, prod: bucket-prod
# Cloudfront: cloudfront-dev-id, cloudfront-stage-id, cloudfront-prod-id
# security-token: token-for-dev, token-for-stage, token-for-prod

name: Evnrironment Handling WF
on:
    workflow_dispatch: 
        inputs:
            environment:
              type: choice
              description: 'Deployment environment'
              options:
                - dev
                - stage
                - prod
jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - run: echo ${{ secrets.SECURITY_TOKEN }}
            - run: echo ${{ vars.S3_BUCKET }}
